## Generate combinations

In [2]:
import numpy as np
import itertools

In [3]:
qt = np.array([0.9,0.95,0.97,0.98,0.99])
th = np.array([0.005,0.01,0.02,0.03,0.05,0.08,0.1,0.15])
dd = np.array([2,3,5,7,8,10])
pct = np.array([0.9,0.95,0.97,0.99,1])

### Solution 1

In [5]:
a = [qt,th,dd, pct]
b = list(itertools.product(*a))
b[:10]

[(0.9, 0.005, 2, 0.9),
 (0.9, 0.005, 2, 0.95),
 (0.9, 0.005, 2, 0.97),
 (0.9, 0.005, 2, 0.99),
 (0.9, 0.005, 2, 1.0),
 (0.9, 0.005, 3, 0.9),
 (0.9, 0.005, 3, 0.95),
 (0.9, 0.005, 3, 0.97),
 (0.9, 0.005, 3, 0.99),
 (0.9, 0.005, 3, 1.0)]

### Solution 2

In [6]:
def cartesian(*arrays):
    mesh = np.meshgrid(*arrays)  # standard numpy meshgrid
    dim = len(mesh)  # number of dimensions
    elements = mesh[0].size  # number of elements, any index will do
    flat = np.concatenate(mesh).ravel()  # flatten the whole meshgrid
    reshape = np.reshape(flat, (dim, elements)).T  # reshape and transpose
    return tuple(reshape)

In [8]:
cartesian(qt,th,dd,pct)[:10]

(array([0.9  , 0.005, 2.   , 0.9  ]),
 array([0.9  , 0.005, 2.   , 0.95 ]),
 array([0.9  , 0.005, 2.   , 0.97 ]),
 array([0.9  , 0.005, 2.   , 0.99 ]),
 array([0.9  , 0.005, 2.   , 1.   ]),
 array([0.9  , 0.005, 3.   , 0.9  ]),
 array([0.9  , 0.005, 3.   , 0.95 ]),
 array([0.9  , 0.005, 3.   , 0.97 ]),
 array([0.9  , 0.005, 3.   , 0.99 ]),
 array([0.9  , 0.005, 3.   , 1.   ]))